name: "CI"

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install shellcheck
          uses: ludeeus/action-shellcheck@master
        - name: Install entr
          run: |
            sudo apt-get update
            sudo apt-get install -y entr
        - name: Run lint and tests
          run: make check
