name: "CI"

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v6
        - name: Setup Rust
          uses: dtolnay/rust-toolchain@stable
        - name: Run lint and tests
          run: make check
