name: "CI"

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup shellcheck
          uses: ludeeus/action-shellcheck@master
        - name: Setup entr
          run: |
            git clone https://github.com/eradman/entr
            cd entr
            ./configure
            make entr
            install entr /usr/local/bin
        - name: Setup BATS
          uses: mig4/setup-bats@v1
        - name: Run lint and tests
          run: make check
