name: "CI"

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install shellcheck
          run: |
            scversion="stable"
            wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
            mkdir -p $HOME/.local/bin
            cp "shellcheck-${scversion}/shellcheck" $HOME/.local/bin/shellcheck
            echo "$HOME/.local/bin" >> $GITHUB_PATH
        - name: Check shell code
          run: make check
